### ISSUE TITLE
Forbidden response when following link in README.md

### ISSUE THREAD

**Issue by TheArtOfEngineering** [dylemma/scala.frp#6]
This link gives me a forbidden response. 
http://lampwww.epfl.ch/%7Eimaier/pub/DeprecatingObserversTR2010.pdf

Is there another link you could post?

**Comment by TheArtOfEngineering** [comment]
I was actually creating a [similar thing](https://github.com/SwiftOnEdge/Reflex) in Swift, and this looks really interesting. I've been calling EventStreams and EventSources as Signals and ColdSignals, but I've been looking to switch to Streams and Spouts or Streams and Sources, and it's nice to see that there is precedent.

**Comment by dylemma** [comment]
Sorry about the delay on this - the notification must have been buried in work stuff. I've updated the links to something that seems to work.

Since the time I put this project together, I've really grown to like [Bacon.js](https://github.com/baconjs/bacon.js) - it's become almost as ubiquitous in my frontend code as jQuery and underscore. You may also want to check out http://reactivex.io/ (seems similar, with a lot more dev power behind it), or https://github.com/nafg/reactive (this project's big brother)
